Papouth/MasterGame

Assets/Scenes/MainScene.unity, Assets/Scripts/Player Scripts/PlayerMovement.cs, Assets/Scripts/Player Scripts/RaycastGrounded.cs, Assets/Scripts/Player Scripts/RaycastGrounded.cs.meta, Assets/Settings/Input System/PlayerMovementInput.cs, Assets/Settings/Input System/PlayerMovementInput.inputactions, ProjectSettings/InputManager.asset, ProjectSettings/TagManager.asset
=> Saut et accroupis

Assets/Scenes/MainScene.unity, Assets/Scripts/Player Scripts/PlayerMovement.cs, Assets/Scripts/Player Scripts/RaycastGrounded.cs
-> anti auto jump de mis
-> patch du joueur qui s'auto redresse
-> patch du joueur qui ne peux pas sauter (réajustement de la hauteur des raycast face au sol)
=> Minor Fix on player movement

Assets/Scenes/Blocking - Test A.unity, Assets/Scenes/Blocking - Test B.unity, Assets/Scenes/Blocking - Test Couloir A-B.unity, UserSettings/Layouts/CurrentMaximizeLayout.dwlt
- Ajout de matériaux pour les test sur les scènes additives, et test additive sur le joueurs.
=> Test scène additive Jury

Assets/Scenes/Blocking - Test Couloir A-B.unity, Assets/Scenes/MainScene.unity, Assets/Scripts/InteractionSystem.meta, Assets/Scripts/InteractionSystem/Interactable.cs, Assets/Scripts/InteractionSystem/Interactable.cs.meta, Assets/Scripts/Objects.meta, Assets/Scripts/Objects/Npc.cs, Assets/Scripts/Objects/Npc.cs.meta, Assets/Scripts/Player Scripts/Interactor.cs, Assets/Scripts/Player Scripts/Interactor.cs.meta, Assets/Scripts/Player Scripts/PlayerMovement.cs, Assets/Settings/Input System/PlayerMovementInput.cs, Assets/Settings/Input System/PlayerMovementInput.inputactions, ProjectSettings/TagManager.asset, UserSettings/EditorUserSettings.asset, UserSettings/Layouts/default-2021.dwlt
Interaction avec la touche "e"
Possibilité d'avoir un texte d'interaction avec le npc / l'objet
=> Interaction System

Assets/Scenes/Tutoriel.meta, Assets/Scenes/Tutoriel/Tutoriel_01_Village.unity, Assets/Scenes/Tutoriel/Tutoriel_01_Village.unity.meta, Assets/Scenes/Tutoriel/Tutoriel_02_Plateforme.unity, Assets/Scenes/Tutoriel/Tutoriel_02_Plateforme.unity.meta, Assets/Scenes/Tutoriel/Tutoriel_03_Tour.unity, Assets/Scenes/Tutoriel/Tutoriel_03_Tour.unity.meta, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/Packages/com.unity.probuilder/Settings.json, ProjectSettings/QualitySettings.asset, UserSettings/EditorUserSettings.asset
AJout de pro builder + Ajout de scène Titré pour le blocking du tutoriel
=> Level design blocking

Assets/Scenes/MainScene.unity, Assets/Scenes/Tutoriel/Tutoriel_01_Village.unity, Assets/Scripts/Player Scripts/PlayerMovement.cs, UserSettings/EditorUserSettings.asset, UserSettings/Layouts/default-2021.dwlt
en commenter, ne fonctionne pas
=> RelativeCamMove

Assets/Animations/MixamoBlocking/WomenSkeletteMixamo.controller, Assets/Scenes/Tutoriel/Tutoriel_01_Village.unity, Assets/Scripts/Player Scripts/PlayerClimb.cs, Assets/Scripts/Player Scripts/PlayerMovement.cs
Petit régalge à droite à gauche
=> petite changement sur caméra

Assets/Animations/Cube.controller, Assets/Animations/Cube.controller.meta, Assets/Animations/DoorEnigmBlocking.anim, Assets/Animations/DoorEnigmBlocking.anim.meta, Assets/Materials/Friction.physicMaterial, Assets/Materials/Friction.physicMaterial.meta, Assets/Prefabs/BlobkingPrefab/CubeBlanc.prefab, Assets/Prefabs/BlobkingPrefab/CubeBleu.prefab, Assets/Prefabs/BlobkingPrefab/CubeNoir.prefab, Assets/Prefabs/BlobkingPrefab/CubeOrange.prefab, Assets/Prefabs/BlobkingPrefab/CubeVert.prefab, Assets/Scenes/MainScene.unity, Assets/Scripts/InteractionSystem/Interactable.cs, Assets/Scripts/Objects/Cube.cs, Assets/Scripts/Objects/Cube.cs.meta, Assets/Scripts/Objects/Door.cs, Assets/Scripts/Objects/Door.cs.meta, Assets/Scripts/Objects/Npc.cs, Assets/Scripts/Objects/Plaque.cs, Assets/Scripts/Objects/Plaque.cs.meta, Assets/Scripts/Player Scripts/PlayerInteractor.cs, ProjectSettings/Packages/com.unity.probuilder/Settings.json, ProjectSettings/TagManager.asset, UserSettings/Layouts/default-2021.dwlt
match the 3 color cube to unlock the door
=> First Blocking Enigme

Assets/Animations/MixamoBlocking/Climbing_Complete.fbx.meta, Assets/Animations/MixamoBlocking/Climbing_Edit.fbx.meta, Assets/Animations/MixamoBlocking/Falling_To_Landing.fbx.meta, Assets/Animations/MixamoBlocking/Idle_Hanging.fbx.meta, Assets/Animations/MixamoBlocking/WomenSkeletteMixamo.controller, Assets/Scenes/MainScene.unity, Assets/Scripts/Player Scripts/PlayerClimb.cs, Assets/Scripts/Player Scripts/PlayerMovement.cs, UserSettings/Layouts/default-2021.dwlt
climb en cours de dev
check des raycasts et réajustement
=> Climb en cours

Assets/Prefabs/PlayerTransform.prefab, Assets/Scenes/MainScene.unity, Assets/Scripts/Player Scripts/PlayerClimb.cs, Assets/Scripts/Player Scripts/PlayerMovement.cs
correction du bug d'animation lié au raycast
=> Push Finished

Assets/Scenes/MainScene.unity, Assets/Scripts/Manager/DialogueManager.cs, Assets/Scripts/Manager/UIManager.cs, Assets/Scripts/Manager/UIManager.cs.meta, Assets/Scripts/Objects/Npc.cs
=> UImanager bug

Assets/Scenes/TestTempo/Passé.unity, Assets/Scenes/TestTempo/Perso.unity, Assets/Scripts/Player Scripts/PlayerTemporel.cs, Assets/Scripts/SceneScript/ObjectSaver.cs, Assets/Scripts/SceneScript/ObjectSaver.cs.meta, Assets/Scripts/SceneScript/PastToPresent.cs, Assets/Scripts/SceneScript/PastToPresent.cs.meta
Possibilité de pousser un objet dans le passé et pas dans le présent
=> Major Update

Assets/Scenes/TestTempo/Passé.unity, Assets/Scenes/TestTempo/Perso.unity, Assets/Scripts/SceneScript/PastToPresent.cs
changement de prefab possible en fonction de la temporalité dans laquelle le joueur se trouve
=> Minor Update

Assets/Scenes/MathisScene.unity
je veux etre pull pitié monsieur
=> Test Mathis

Assets/Animations/MixamoBlocking/WomenSkeletteMixamo.controller, Assets/Animations/NewClimbAnimation/Braced Hang Drop Down.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang Drop Ground.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang Jump Left.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang Jump Right.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang Jump Up.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang MoveLeft.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang MoveRight.fbx.meta, Assets/Animations/NewClimbAnimation/Braced Hang To Climb.fbx.meta, Assets/Animations/NewClimbAnimation/Hanging Idle.fbx.meta, Assets/Scenes/MainScene.unity, Assets/Scripts/Player Scripts/PlayerMovement.cs, Assets/Scripts/PlayerNewClimbSystem.cs
problème  d'animation lié au perso qui ne veut pas se bloquer a une pos donné
=> NewClimb en cours

Assets/Animations/MixamoBlocking/WomenSkeletteMixamo.controller, Assets/Prefabs/PlayerTransform.prefab, Assets/Scenes/MainScene.unity, Assets/Scripts/Player Scripts/PlayerMovement.cs, Assets/Scripts/PlayerNewClimbSystem.cs, ProjectSettings/TagManager.asset
Pour le moment on peut grimper sur les layers ClimbLayer. Le joueur peut se déplacer sur ceux ci, pour le moment.
Les déplacements sont inversés par contre
=> Climb Update

Assets/Prefabs/PlayerTransform.prefab, Assets/Scenes/TestTempo/EssentialComponent.unity, Assets/Scenes/TestTempo/Passé.unity, Assets/Scripts/CustomTriggers/LiftableObject.cs, Assets/Scripts/SceneScript/PastToPresent.cs
plante evolutive en partie fonctionnel
reste des bugs de placement à corriger
=> Update Plante Evo

Assets/Scenes/MenuScene/EssentialComponent.unity, Assets/Scenes/MenuScene/MainMenuScene.unity, Assets/Scripts/UI/MenuManager.cs
Temporaire scène menu blocking inspiré du concept art de océane
=> Scene Main menu

Assets/Prefabs/Enigme.meta, Assets/Prefabs/Enigme/PlateformeComplet.prefab, Assets/Prefabs/Enigme/PlateformeComplet.prefab.meta, Assets/Scenes/TheoScene.unity, Assets/Scripts/CustomsEvents/Plateforme.cs
Bug Kali Set Parent ne fonctionne pas du surement à un override de transform dans un script de déplacement, à voir avec Louis pour régler ca
=> Plateforme Code

.gitignore, Assets/Prefabs/Enigme/PlateformeComplet.prefab, Assets/Scenes/0_MenuScene/EssentialComponent.unity, Assets/Scenes/2_Tutoriel/Tutoriel_01_Passe.unity, Assets/Scenes/2_Tutoriel/Tutoriel_01_Present.unity, Assets/Scripts/CustomTriggers/Leviers.cs, Assets/Scripts/CustomsEvents/Plateforme.cs, UserSettings/Layouts/default-2021.dwlt
ajout de la plateforme par levier + modif dans le script afin d'avoir un mouvement continu
=> Fix plateforme

.gitignore, Assets/Prefabs/Player/Player_Kali.prefab, Assets/Scenes/0_MenuScene/EssentialComponent.unity, Assets/Scenes/2_Tutoriel/Tutoriel_01_Present.unity, Assets/Scripts/Player Scripts/PlayerNewClimbSystem.cs, Assets/Scripts/System/RespawnPlayer.cs, Assets/Scripts/System/RespawnSystem.cs, Assets/Scripts/System/VideRespawn.cs, UserSettings/Layouts/default-2021.dwlt
opti du climb system + fix de bug qui était créée avec l'ancien
=> Rework Climb
